version: "3"

services:
  mongodb:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
  
  mongo-setup:
    build: ./db/mongodb-setup
    links:
      - mongodb

  api:
    build: .
    links:
      - mongodb
    ports:
      - "5000:5000"
